### ISSUE TITLE
UI framework implementation

### ISSUE THREAD

**Issue by yz89** [yz89/substrate-nfts#1]
We need to introduce the cennznet-ui framework under a called "ui" directory.

https://github.com/cennznet/cennznet-ui

**Comment by alanpoon** [comment]
I think you will also need to change to use cennznet's runtime

**Comment by yz89** [comment]
Isn't it using wasm files for deployment? Is cennznet's runtime necessary?

**Comment by alanpoon** [comment]
You are right about the wasm, but I thought it would be best practice. I will check if cennznet's runtime is required for the assignment.
Looks console.onfinality also supports other runtime.
![Screenshot from 2019-08-03 11-47-10](https://user-images.githubusercontent.com/8205468/62407029-83357380-b5e4-11e9-9ce6-a15c4785697b.png)

**Comment by yz89** [comment]
Ok, and if we implemented with substrate runtime we easily use cennznet's runtime.
